POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "meu fff",
    "details": null,
    "maximumAttendees": null
}

###

POST http://localhost:3333/events/9db470fd-317f-4507-9f05-82b728dca5eb/attendees
Content-Type: application/json

{
    "name": "Julaa Kniest",
    "email": "jk@gmail.com"
}

###
GET http://localhost:3333/events/9db470fd-317f-4507-9f05-82b728dca5eb

###
GET http://localhost:3333/attendees/13/check-in

###

GET http://localhost:3333/events/9db470fd-317f-4507-9f05-82b728dca5eb/attendees